# dan editor configuration
# Copy to ~/.config/dan/config.toml to customise

# Wrap long lines (true) or scroll horizontally (false)
# Note: toggle in app with ^G
wrap_lines = true

# Tab width in spaces.
tab_width = 4

# Expand tabs to spaces (true = spaces, false = literal tabs)
expand_tab = false

# Show line numbers in the toolbar
line_numbers = true

# Highlight active line
highlight_active = true 

# Enable syntax highlighting based on file extension
syntax_highlight = true

# Fast scroll lines when jumping via Ctrl+Shift+Up/Down
fast_scroll_steps = 10
 

# Lines of offset/padding to keep above/below the cursor when scrolling
# Note: If the terminal window has less than 20 lines, the offset is automatically 0
scroll_off = 3

# Auto-close pairs: "'`({[
# TODO: not implemented
auto_close = true

# Color theme
# TODO: not implemented
theme = "default"

# Always show label "^H Help" in the toolbar
show_help = true

# Show document character encoding in the toolbar (e.g. "utf-8")
show_encoding = true

# Show detected language in the toolbar (e.g. "Rust")
show_lang = true
